apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: streamingapp
  region: ap-south-1
  version: "1.29"

iam:
  withOIDC: true

vpc:
  nat:
    gateway: Single

managedNodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: false
    labels:
      workload: streamingapp
    iam:
      withAddonPolicies:
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
